In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("Downloads/ML/knn.csv")

In [4]:
df

    Weight(x2)  Height(y2)        Class
0           51         167  Underweight
1           66         177       Normal
2           75         169   Overweight
3           69         176       Normal
4           50         173  Underweight
5           82         170   Overweight
6           65         172       Normal
7           58         180  Underweight
8           68         162   Overweight
9           63         165       Normal
10          52         174  Underweight
11          58         169       Normal
12          78         162   Overweight
13          65         168       Normal
14          62         183  Underweight
15          72         180       Normal
16          80         180   Overweight
17          60         178  Underweight
18          57         173       Normal
19          73         164   Overweight
20          53         170  Underweight
21          74         182       Normal
22          72         175   Overweight
23          53         163       Normal
24          55         180  Underweight

## KNN (K-Nearest Neighbour)